root = "."
tmp_dir = "tmp"

[build]
  # Use .exe directly for Windows
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  # Use OS condition to determine bin
  bin = "./tmp/main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[screen]
  clear_on_rebuild = true