basePath: /api/v1
definitions:
  errors.AppError:
    properties:
      code:
        type: integer
      detail:
        type: string
      message:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
      updated_at:
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8386
info:
  contact: {}
  description: API documentation cho ứng dụng Fiber
  title: Fiber API
  version: "1.0"
paths:
  /users:
    get:
      description: Lấy danh sách tất cả users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Lấy danh sách users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Tạo một user mới với thông tin được cung cấp
      parameters:
      - description: User Info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Tạo user mới
      tags:
      - users
  /users/{id}:
    get:
      description: Lấy thông tin chi tiết của user bằng ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/errors.AppError'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/errors.AppError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Lấy user bằng ID
      tags:
      - users
swagger: "2.0"
