// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID            int32            `json:"id"`
	UserID        int32            `json:"user_id"`
	Token         string           `json:"token"`
	ExpiresAt     pgtype.Timestamp `json:"expires_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	LastUsedAt    pgtype.Timestamp `json:"last_used_at"`
	UsageCount    int32            `json:"usage_count"`
	LastUsedIP    string           `json:"last_used_ip"`
	LastUserAgent string           `json:"last_user_agent"`
}

type User struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
